# Generated by Django 5.2.8 on 2025-12-02 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_rename_organizationname_formregistration_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='formregistration',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
